(function(){'use strict';const C=StudyCore,B=StudyBank,formats=['글','도식','인터랙티브 웹','설명 영상'],K='understanding-human-pilot-v1';const app=document.querySelector('#app'),status=document.querySelector('#status');let s=null;const now=()=>new Date().toISOString(),note=t=>status.textContent=t;
 function put(){try{localStorage.setItem(K,JSON.stringify(s))}catch{note('이 환경에서는 기기에 저장하지 못했어요. 완료 후 JSON을 꼭 내보내 주세요.')}}
 function el(tag,text,attrs={}){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
 function button(text,fn,cls=''){const e=el('button',text,{type:'button'});if(cls)e.className=cls;e.onclick=fn;return e}
 function clear(title){app.replaceChildren();if(title)app.append(el('h2',title));note('')}
 function exportData(){if(!s)return;const data=JSON.stringify({...s,exported_at:now(),evidence_scope:'Self-declared human submission, not verified participant identity or an efficacy certificate'},null,2),a=el('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download='understanding-'+s.kind+'-'+s.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000);note('JSON을 내보냈어요. 원하면 이 파일을 직접 공유해 주세요. 자동 전송은 하지 않았어요.')}
 function deleteData(){if(!confirm('이 기기에 저장한 평가 답변을 지울까요? 이미 내보낸 파일은 직접 삭제해야 합니다.'))return;try{localStorage.removeItem(K)}catch{}s=null;home();note('기기의 평가 답변을 지웠어요.')}
 function home(){clear();const p=el('section');p.append(el('h2','시작 전에'),el('p','자발적으로 참여하고 언제든 중단할 수 있어요. 이해도 평가는 세 주제 중 하나와 네 형식 중 하나를 무작위로 배정합니다. 한 사람이 같은 설명을 네 번 보는 반복 학습을 피하려는 설계예요. 청취 평가는 별도 세션으로 진행합니다.'));
 [['consent','참여와 기기 내 답변 저장에 동의합니다.'],['human','AI 대리 응답이 아닌, 사람이 직접 읽고 답합니다.']].forEach(([id,text])=>{const l=el('label');l.append(el('input',undefined,{type:'checkbox',id}),document.createTextNode(text));p.append(l)});
 const knowledge=el('select',undefined,{id:'knowledge','aria-label':'이 주제 설명을 본 경험'});['설명 자료를 아직 보지 않았다','일부 또는 전부를 이미 보았다','잘 모르겠다'].forEach((v,i)=>knowledge.append(el('option',v,{value:String(i)})));p.append(el('p','이 실험실의 설명을 이미 본 적 있나요?'),knowledge);
 function start(kind){try{C.requireConsent({consent:document.querySelector('#consent').checked,human:document.querySelector('#human').checked})}catch{note('두 동의 항목을 확인해야 시작할 수 있어요.');return}if(s){note('기존 세션을 먼저 내보내고 지워야 새 평가를 시작할 수 있어요.');return}const draw=()=>crypto.getRandomValues(new Uint32Array(1))[0];s={schema_version:1,study_version:'1.1.0-pilot1',id:Array.from(crypto.getRandomValues(new Uint32Array(4))).join('-'),kind,participant_mode:'self_declared_human',human:true,identity_verified:false,synthetic:window.__studyQA===true,consent:true,started_at:now(),prior_exposure:Number(knowledge.value),viewport:{width:innerWidth,height:innerHeight},responses:{},timings:{},phase:kind==='learning'?'pre':'listening'};if(kind==='learning'){const a=C.assign(B.length,draw);s.topic=B[a.topic].id;s.format=a.format;s.artifact_fingerprints=(window.StudyContent[s.topic]||{}).fingerprints||{}}else{s.topic='next-token';s.artifact_fingerprints=(window.StudyContent['next-token']||{}).fingerprints||{}}put();render()}
 p.append(button('이해도 평가 시작',()=>start('learning')),button('자막·청취 평가 시작',()=>start('listening'),'secondary'));app.append(p);
 if(s){const r=el('section');r.append(el('h2','이 기기의 저장된 평가'),el('p',s.kind==='learning'?'이해도 평가 세션이 있어요.':'자막·청취 평가 세션이 있어요.'),button('이어 하기',render),button('JSON 내보내기',exportData,'secondary'),button('기기 답변 지우기',deleteData,'secondary'));app.append(r)}
 }
 function bank(){return B.find(b=>b.id===s.topic)}
 function quiz(phase){const b=bank(),qs=b[phase];clear(phase==='pre'?'설명을 보기 전: 지금 생각대로 답해 주세요':phase==='post'?'설명을 본 뒤: 바뀐 예측을 확인해 주세요':'시간이 지난 뒤: 설명을 다시 보지 말고 답해 주세요');app.append(el('p',b.title+' · '+formats[s.format]),el('p','모르면 “모르겠다”를 골라도 괜찮아요. 사전 정답은 지금 공개하지 않습니다.'));const f=el('form');qs.forEach((q,i)=>{const field=el('fieldset');field.append(el('legend',q.text));q.options.forEach((o,j)=>{const l=el('label');l.append(el('input',undefined,{type:'radio',name:'q'+i,value:String(j),required:'',id:phase+'-'+i+'-'+j}),document.createTextNode(o));field.append(l)});f.append(field)});if(phase==='retention'){const l=el('label');l.append(el('input',undefined,{type:'checkbox',id:'retentionCrossover'}),document.createTextNode('사후 평가 뒤 다른 설명을 보거나 청취 평가에도 참여했다'));f.append(l)}const submit=el('button',phase==='pre'?'설명 보기':'답변 완료',{type:'submit'});f.append(submit);const begun=Date.now();f.onsubmit=e=>{e.preventDefault();const a=qs.map((_,i)=>Number(new FormData(f).get('q'+i)));C.score(qs,a);s.responses[phase]=a;s.timings[phase+'_wall_seconds']=(Date.now()-begun)/1000;if(phase==='pre'){s.phase='exposure';s.exposure_started_at=now()}else if(phase==='post'){s.phase='complete';s.completed_at=now()}else{s.phase='complete';s.retention_completed_at=now();s.retention_cross_format_exposure=document.querySelector('#retentionCrossover').checked}put();render()};app.append(f)}
 function exposure(){const b=bank(),content=StudyContent[s.topic];clear('설명을 보고 직접 확인해 주세요');app.append(el('p',b.title+' · 배정된 형식: '+formats[s.format]),el('p','필요한 만큼 읽거나 조작하세요. 한 번에 한 형식만 노출하려는 설계이며, 다른 자료를 함께 봤다면 다음 단계에서 표시해 주세요.'));
 const box=el('section');if(s.format===0){const p=el('div',content.writing,{class:'writing'});box.append(p)}else if(s.format===1)box.append(el('img',undefined,{src:b.root+'diagram.svg',alt:b.title+'의 인과·절차 도식'}));else if(s.format===2)box.append(el('iframe',undefined,{src:b.root+'index.html?study-format=web',title:b.title+' 인터랙티브 웹',loading:'eager'}));else{const v=el('video',undefined,{src:b.root+content.video,controls:'',playsinline:'',preload:'metadata'});box.append(v)}app.append(box);
 const l=el('label');l.append(el('input',undefined,{type:'checkbox',id:'crossover'}),document.createTextNode('배정된 형식 외에 다른 설명도 봤다'));app.append(l,el('p','기록되는 시간은 이 단계의 벽시계 시간이며, 집중 시간이나 실제 시청 시간을 보증하지 않습니다.',{class:'muted'}),button('설명을 다 봤어요 · 사후 질문으로',()=>{s.timings.exposure_wall_seconds=(Date.now()-Date.parse(s.exposure_started_at))/1000;s.cross_format_exposure=document.querySelector('#crossover').checked;s.phase='post';put();render()}))}
 function listening(){clear('한국어 자막 · 영어 음성 청취 평가');app.append(el('p','영상 속 한국어 자막이 읽히는지, 말소리와 맞는지 직접 확인해 주세요. 이 답변은 이해도 점수와 섞지 않습니다. 장치에서 실제 소리가 들렸는지는 본인이 판단합니다.'));const v=el('video',undefined,{src:'../video/video-ko.mp4',controls:'',playsinline:'',preload:'metadata',id:'listeningVideo'});let last=0,observed=0;v.ontimeupdate=()=>{const d=v.currentTime-last;if(!v.paused&&!v.seeking&&!v.muted&&v.volume>0&&d>0&&d<=1)observed+=d;last=v.currentTime};app.append(v);const f=el('form');const questions=[['audibility','실제 말소리가 들렸나요?',['분명히 들렸다','잘 들리지 않았다','듣지 못했다 / 판단 불가']],['readability','휴대폰 또는 현재 화면에서 자막은?',['읽기 편하다','글자가 작다','속도가 빠르다','겹치거나 잘린다','판단 불가']],['synchronization','음성과 자막의 타이밍은?',['대체로 맞는다','자막이 먼저 나온다','자막이 늦다','영어를 듣고 비교하기 어렵다']],['english_comprehension','영어 내레이션은 어느 정도 이해했나요?',['대부분 이해','일부 이해','한국어 자막 위주로 이해','판단 불가']]];questions.forEach(([name,text,options])=>{const fs=el('fieldset');fs.append(el('legend',text));options.forEach((o,i)=>{const l=el('label');l.append(el('input',undefined,{type:'radio',name,value:String(i),required:''}),document.createTextNode(o));fs.append(l)});f.append(fs)});f.append(el('label','불편한 지점이나 시각이 있다면 적어 주세요. 이름·연락처 같은 개인정보는 쓰지 마세요.',{for:'comment'}),el('textarea',undefined,{id:'comment',name:'comment',rows:'3',maxlength:'500'}),el('button','청취 평가 완료',{type:'submit'}));f.onsubmit=e=>{e.preventDefault();const d=new FormData(f);s.responses.listening=Object.fromEntries(questions.map(([n])=>[n,Number(d.get(n))]));s.responses.comment=d.get('comment');s.timings.observed_unmuted_media_progress_seconds=observed;s.playback_metadata={muted_at_submission:v.muted,volume_at_submission:v.volume,audible_output_verified:false};s.phase='complete';s.completed_at=now();put();render()};app.append(f)}
 function complete(){clear('평가 기록을 확인해 주세요');if(s.synthetic)app.append(el('p','자동화 QA용 합성 세션입니다. 사람 결과에 포함하면 안 됩니다.',{class:'warning'}));if(s.kind==='learning'){const b=bank(),pre=C.score(b.pre,s.responses.pre),post=C.score(b.post,s.responses.post);app.append(el('p',b.title+' · '+formats[s.format]),el('p','사전 '+pre.correct+'/'+pre.total+' · 사후 '+post.correct+'/'+post.total),el('p','개인의 탐색용 결과예요. 문항 난이도, 사전 노출, 집중도와 우연을 통제하지 않았으므로 이 차이를 형식의 인과 효과나 일반 학습 성과라고 해석할 수 없습니다.',{class:'warning'}));if(!s.retention_completed_at){const wait=24*60*60*1000;const ready=Date.now()-Date.parse(s.completed_at)>=wait;const bt=button('하루 뒤 회상 질문',()=>{if(Date.now()-Date.parse(s.completed_at)<wait){note('사후 답변 완료 후 하루가 지난 다음 참여해 주세요.');return}s.phase='retention';put();render()},'secondary');bt.disabled=!ready;app.append(el('p','같은 기기에서 하루 뒤 다시 열면, 자료를 다시 보지 않고 회상 질문에 답할 수 있어요. 청취 평가나 다른 설명을 먼저 봤다면 해석에 주의해야 합니다.'),bt)}else{const r=C.score(b.retention,s.responses.retention);app.append(el('p','지연 회상 '+r.correct+'/'+r.total))}}else app.append(el('p','청취·가독성·타이밍의 자기보고를 기록했어요. 자동 검사나 번역 인증으로 바꾸지 않습니다.'));
 app.append(button('JSON 내보내기 · 직접 공유하기',exportData),button('기기 답변 지우기',deleteData,'secondary'),el('p','파일을 Sung의 대화에 첨부하면 제출된 응답으로 검토할 수 있어요. 개인정보를 쓰지 않았는지 먼저 확인해 주세요.',{class:'muted'}))}
 function render(){if(!s)return home();if(['pre','post','retention'].includes(s.phase))quiz(s.phase);else if(s.phase==='exposure')exposure();else if(s.phase==='listening')listening();else if(s.phase==='complete')complete();else{note('저장된 단계가 올바르지 않아요.');home()}}
 try{const stored=JSON.parse(localStorage.getItem(K));if(stored&&stored.schema_version===1&&stored.study_version==='1.1.0-pilot1'&&stored.consent===true&&['learning','listening'].includes(stored.kind))s=stored}catch{}home();window.StudyUI={getSession:()=>structuredClone(s),exportData};
})();
